# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Gallery"
subtitle: "ZCX@2022"
author:  "ZCX"
header:
 title: "Photography"
 subtitle: "by ZCX"
footer:
 name: "ZCX's Portrait Photography"
 bio: "A photographer, a senior undergraduate in PKU, and a former chief editor in photography of PKU's Official Weibo/Wechat Account. See my scenery photography"
social_urls:
  weixin: "ZCX__2001"
  qq: "576587568"
  mail: "Mailto:peterzhu@pku.edu.cn"
  # github: "https://github.com/FreeButUselessSoul"

theme: jekyll-theme-slate
