# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Gallery"
subtitle: "ZCX,HQ@2022"
author:  "ZCX"
header:
 title: "Photography"
 subtitle: "by ZCX"
footer:
 name: "ZCX Here."
 bio: "a photographer in PKU, former chief editor in photography of PKU's Official Weibo/Wechat Account."
social_urls:
  weixin: "ZCX__2001"
  qq: "576587568"
  mail: "Mailto:peterzhu@pku.edu.cn"
  # github: "https://github.com/FreeButUselessSoul"

theme: jekyll-theme-slate
